# Generated by Django 3.2.13 on 2022-06-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(blank=True, null=True)),
                ('text_to_voice', models.FileField(null=True, upload_to='audio/')),
                ('ans_1', models.CharField(blank=True, max_length=200, null=True)),
                ('ans_2', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_P', to='base.lesson')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_P_T', to='quiz.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='audio/')),
                ('text_to_voice', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lesson')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_M_T', to='quiz.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(blank=True, max_length=200, null=True)),
                ('op2', models.CharField(blank=True, max_length=200, null=True)),
                ('op3', models.CharField(blank=True, max_length=200, null=True)),
                ('op4', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.departmant')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_C', to='base.lesson')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_C_T', to='quiz.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_exam', to='base.departmant')),
            ],
        ),
    ]
