# Generated by Django 3.2.13 on 2022-06-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='departmant',
        ),
        migrations.RemoveField(
            model_name='questionmatch',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='questionmatch',
            name='type_question',
        ),
        migrations.RemoveField(
            model_name='questionpractice',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='questionpractice',
            name='type_question',
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.lesson')),
                ('q_choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionchoice')),
                ('q_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionmatch')),
                ('q_practice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionpractice')),
            ],
        ),
    ]
