# Generated by Django 3.2.13 on 2022-06-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('quiz', '0002_auto_20220604_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='type_question',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='deparmtant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.departmant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
