# Generated by Django 3.2.13 on 2022-06-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220604_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionchoice',
            old_name='deparmtant',
            new_name='departmant',
        ),
    ]
