# Generated by Django 3.2.13 on 2022-06-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_teacher_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='teacher',
        ),
    ]
