# Generated by Django 3.2.13 on 2022-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220610_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='departmant',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
