# Generated by Django 3.2.13 on 2022-06-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('lesson_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leeson_departmant', to='base.departmant')),
            ],
        ),
        migrations.CreateModel(
            name='WarmUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('videofile', models.FileField(null=True, upload_to='videos/')),
                ('lesson_warmup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='base.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionDepartmant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_departmant', to='base.departmant')),
            ],
        ),
        migrations.CreateModel(
            name='ContentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('content', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_lesson', to='base.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ContentDepartmant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('content', models.TextField(blank=True, null=True)),
                ('departmant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_departmant', to='base.departmant')),
            ],
        ),
    ]
